site_name: noelbird techlog
theme:
  name: material
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
      

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css # highlight
extra_javascript:
  - javascripts/config.js # common configuration
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js # highlight
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # for mathjax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # for mathjax
nav:
  - C++ Deep Learning:
    - intro: cpp-deep-learning/01.md
    - 'day1: 이미지 load & show': cpp-deep-learning/02.md
    - 'day2: 화소 영역 처리 중 rotate & convolve': cpp-deep-learning/03.md
    - 'day3: convolve operator': cpp-deep-learning/04.md
    - 'day4: fully-connected layer & network': cpp-deep-learning/05.md
    - 'day5: backpropage & done first commit': cpp-deep-learning/06.md
  - OS making:
    - 'index': os-making/index.md
    - 'day1: bootstrap 만들기': os-making/01.md
    - 'day2: bootloader 만들기': os-making/02.md
    - 'day3: protected mode 진입': os-making/03.md
    - 'day4: protected mode 진입(2)': os-making/04.md
    - 'day5: 인터럽트와 예외': os-making/05.md
  - spring:
    - intro: spring/01.md
  - 꿀팁:
    - 'github multi-user': 'honeytip/github-multiuser-one-pc.md'
    - 'github에 이미 push된 파일 제외': 'honeytip/github-remove-added-file.md'
    - 'books':
      - 'index': 'honeytip/books/index.md'
      - '01: 프런트엔드 개발자 시작하기': 'honeytip/books/1.md'
      - '02: 밑바닥부터 시작하는 딥러닝 ': 'honeytip/books/2.md'
      - '03: 만들면서 배우는 OS 구조와 원리': 'honeytip/books/3.md'
    - 'linux kernel contribution guide': 'honeytip/kernel-contribution-guide.md'
    
  - whoami: whoami/aboutme.md
  - daily:
    - 2021년 5월:
      - '2021-05-24': 'daily/2021-05-24.md'
      - '2021-05-21': 'daily/2021-05-21.md'
      - '2021-05-19': 'daily/2021-05-19.md'
      - '2021-05-18': 'daily/2021-05-18.md'
      - '2021-05-17': 'daily/2021-05-17.md'
      - '2021-05-16': 'daily/2021-05-16.md'
      - '2021-05-15': 'daily/2021-05-15.md'
      - '2021-05-14': 'daily/2021-05-14.md'
      - '2021-05-13': 'daily/2021-05-13.md'
      - '2021-05-12': 'daily/2021-05-12.md'
      - '2021-05-11': 'daily/2021-05-11.md'
      - '2021-05-10': 'daily/2021-05-10.md'
      - '2021-05-09': 'daily/2021-05-09.md'
      - '2021-05-06': 'daily/2021-05-06.md'
      - '2021-05-04': 'daily/2021-05-04.md'
      - '2021-05-03': 'daily/2021-05-03.md'
      - '2021-05-02': 'daily/2021-05-02.md'
      - '2021-05-01': 'daily/2021-05-01.md'
    - 2021년 4월:
      - '2021-04-30': 'daily/2021-04-30.md'
      - '2021-04-29': 'daily/2021-04-29.md'
      - '2021-04-28': 'daily/2021-04-28.md'
      - '2021-04-27': 'daily/2021-04-27.md'
      - '2021-04-24': 'daily/2021-04-24.md'
      - '2021-04-23': 'daily/2021-04-23.md'
      - '2021-04-19': 'daily/2021-04-19.md'
      - '2021-04-18': 'daily/2021-04-18.md'
      - '2021-04-17': 'daily/2021-04-17.md'
      - '2021-04-16': 'daily/2021-04-16.md'
      - '2021-04-15': 'daily/2021-04-15.md'
      - '2021-04-14': 'daily/2021-04-14.md'
      - '2021-04-10': 'daily/2021-04-10.md'
      - '2021-04-09': 'daily/2021-04-09.md'
      - '2021-04-08': 'daily/2021-04-08.md'
      - '2021-04-07': 'daily/2021-04-07.md'
      - '2021-04-06': 'daily/2021-04-06.md'
    - 2021년 3월:
      - '2021-03-29': 'daily/2021-03-29.md'
      - '2021-03-28': 'daily/2021-03-28.md'
      - '2021-03-24': 'daily/2021-03-24.md'
      - '2021-03-22': 'daily/2021-03-22.md'
      - '2021-03-11': 'daily/2021-03-11.md'
      - '2021-03-11-2': 'daily/2021-03-11-2.md'
      - '2021-03-09': 'daily/2021-03-09.md'
      - '2021-03-04': 'daily/2021-03-04.md'
      - '2021-03-01': 'daily/2021-03-01.md'
    - 2021년 2월:
      - '2021-02-22': 'daily/2021-02-22.md'
      - '2021-02-21': 'daily/2021-02-21.md'
    
    
