site_name: noelbird techlog
theme:
  name: material
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - attr_list

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css # highlight
extra_javascript:
  - javascripts/config.js # common configuration
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js # highlight
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # for mathjax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # for mathjax
extra:
  analytics:
    provider: google
    property: G-SQ8EXBDW54
nav:
  - BASIC:
    - OS making:
      - 'index': os-making/index.md
      - 'day1: bootstrap 만들기': os-making/01.md
      - 'day2: bootloader 만들기': os-making/02.md
      - 'day3: protected mode 진입': os-making/03.md
      - 'day4: protected mode 진입(2)': os-making/04.md
      - 'day5: 인터럽트와 예외': os-making/05.md
      - 'day6: IDT': os-making/06.md
      - 'day7: PIC의 초기화': os-making/07.md
      - 'day8: PIC - 설명(1)': os-making/08.md
      - 'day9: PIC - 설명(2)': os-making/09.md
      - 'day10: PIC - 타이머': os-making/10.md
      - 'day11: interrupt/exception 마무리': os-making/11.md
      - 'day12: task switching': os-making/12.md
      - 'day13: task switching(2)': os-making/13.md
      - 'day14: task switching(3)': os-making/14.md
      - 'day15: task switching(4)': os-making/15.md
      - 'day16: call을 이용한 task switching': os-making/16.md
      - 'day17: protection': os-making/17.md
      - 'day18: protection': os-making/18.md
      - 'day19: usermode_task_switching': os-making/19.md
      - 'day20: usermode_task_switching(2)': os-making/20.md
    - interpreter:
      - 'index': interpreter/index.md
      - 'day1: 렉싱': interpreter/01.md
      - 'day2': interpreter/02.md
      - 'day3': interpreter/03.md
      - 'day4': interpreter/04.md
  - APPLICATION:
    - Deep Learning:
      - C++ Deep Learning:
        - intro: cpp-deep-learning/01.md
        - 'day1: 이미지 load & show': cpp-deep-learning/02.md
        - 'day2: 화소 영역 처리 중 rotate & convolve': cpp-deep-learning/03.md
        - 'day3: convolve operator': cpp-deep-learning/04.md
        - 'day4: fully-connected layer & network': cpp-deep-learning/05.md
        - 'day5: backpropage & done first commit': cpp-deep-learning/06.md
    - Neural Information Retrieval:
      - overview: 'nir/overview.md'
      # - 'day1: bm25': 'nir/bm25.md'
      # - 'day2: qna bert': 'nir/qnabirt.md'
    - web:
      - spring:
        - intro: spring/index.md
        - 'day1: spring 시작': spring/01.md
      - nextjs:
        - index: nextjs/index.md
        - 'day1: Next.js / navigate between pages / assets, metadata, css': 'nextjs/01.md'
      - html-canvas:
        - index: html-canvas/index.md
        - 'day1: canvas 사용하기': html-canvas/1.md
  - 꿀팁:
    - 'github multi-user': 'honeytip/github-multiuser-one-pc.md'
    - 'github에 이미 push된 파일 제외': 'honeytip/github-remove-added-file.md'
    - 'books':
      - 'index': 'honeytip/books/index.md'
      - '1: 프런트엔드 개발자 시작하기': 'honeytip/books/1.md'
      - '2: 밑바닥부터 시작하는 딥러닝 ': 'honeytip/books/2.md'
      - '3: 만들면서 배우는 OS 구조와 원리': 'honeytip/books/3.md'
      - '4: 파이썬 웹 프로그래밍': 'honeytip/books/4.md'
      - '5: 컨테이너 인프라 환경 구축을 위한 쿠버네티스 도커': 'honeytip/books/5.md'
      - '6: 넷플릭스: 규칙없음': 'honeytip/books/6.md'
    - 'reading matters':
      - 'index': 'honeytip/reading_matters/index.md'
      - '1: 이상한 모임': 'honeytip/reading_matters/1.md'
    - 'conference_reviews':
      - '카카오를 지탱하는 기술': 'honeytip/conference_reviews/2020_kakao_if/tech_supporting_kakao.md'
    - 'conference_reviews2021':
      - 'naver deview': 'honeytip/conference_reviews/2021_naver_deview/transformer_tip.md'
    - 'linux kernel contribution guide': 'honeytip/kernel-contribution-guide.md'
    - 'javascript game making. using canvas': 'honeytip/jsgame/README.md'
    - '후원 받기(도네리카노)': 'honeytip/donaricano.md'
    - 'vscode에 fira font 적용': 'honeytip/fira-font.md'
  - 회고:
    - '2021': 'self-feedback/2021.md'
  
    
  - whoami: whoami/aboutme.md
  - daily:
    - 2022년 1월:
      - '2022-01-03': 'daily/2022-01-03.md'
    - 2021년 11월:
      - '2021-11-26': 'daily/2021-11-26.md'
    - 2021년 9월:
      - '2021-10-31': 'daily/2021-10-31.md'
      - '2021-10-18': 'daily/2021-10-18.md'
      - '2021-10-15': 'daily/2021-10-15.md'
      - '2021-10-10': 'daily/2021-10-10.md'
      - '2021-10-04': 'daily/2021-10-04.md'
      - '2021-10-03': 'daily/2021-10-03.md'
      - '2021-10-02': 'daily/2021-10-02.md'
      - '2021-09-19': 'daily/2021-09-19.md'
      - '2021-09-18': 'daily/2021-09-18.md'
      - '2021-09-04': 'daily/2021-09-04.md'
    - 2021년 8월:
      - '2021-08-28': 'daily/2021-08-28.md'
      - '2021-08-27': 'daily/2021-08-27.md'
      - '2021-08-25': 'daily/2021-08-25.md'
      - '2021-08-11': 'daily/2021-08-11.md'
      - '2021-08-09': 'daily/2021-08-09.md'
      - '2021-08-05': 'daily/2021-08-05.md'
      - '2021-08-03': 'daily/2021-08-03.md'
      - '2021-08-02': 'daily/2021-08-02.md'
      - '2021-08-01': 'daily/2021-08-01.md'
    - 2021년 7월:
      - '2021-07-30': 'daily/2021-07-30.md'
      - '2021-07-28': 'daily/2021-07-28.md'
      - '2021-07-27': 'daily/2021-07-27.md'
      - '2021-07-26': 'daily/2021-07-26.md'
      - '2021-07-25': 'daily/2021-07-25.md'
      - '2021-07-24': 'daily/2021-07-24.md'
      - '2021-07-23': 'daily/2021-07-23.md'
      - '2021-07-22': 'daily/2021-07-22.md'
      - '2021-07-20': 'daily/2021-07-20.md'
      - '2021-07-19': 'daily/2021-07-19.md'
      - '2021-07-17': 'daily/2021-07-17.md'
      - '2021-07-16': 'daily/2021-07-16.md'
      - '2021-07-14': 'daily/2021-07-14.md'
      - '2021-07-10': 'daily/2021-07-10.md'
      - '2021-07-08': 'daily/2021-07-08.md'
      - '2021-07-06': 'daily/2021-07-06.md'
      - '2021-07-01': 'daily/2021-07-01.md'
    - 2021년 6월:
      - '2021-06-30': 'daily/2021-06-30.md'
      - '2021-06-29': 'daily/2021-06-29.md'
      - '2021-06-26': 'daily/2021-06-26.md'
      - '2021-06-24': 'daily/2021-06-24.md'
      - '2021-06-22': 'daily/2021-06-22.md'
      - '2021-06-21': 'daily/2021-06-21.md'
      - '2021-06-02': 'daily/2021-06-02.md'
    - 2021년 5월:
      - '2021-05-27': 'daily/2021-05-27.md'
      - '2021-05-26': 'daily/2021-05-26.md'
      - '2021-05-25': 'daily/2021-05-25.md'
      - '2021-05-24': 'daily/2021-05-24.md'
      - '2021-05-21': 'daily/2021-05-21.md'
      - '2021-05-19': 'daily/2021-05-19.md'
      - '2021-05-18': 'daily/2021-05-18.md'
      - '2021-05-17': 'daily/2021-05-17.md'
      - '2021-05-16': 'daily/2021-05-16.md'
      - '2021-05-15': 'daily/2021-05-15.md'
      - '2021-05-14': 'daily/2021-05-14.md'
      - '2021-05-13': 'daily/2021-05-13.md'
      - '2021-05-12': 'daily/2021-05-12.md'
      - '2021-05-11': 'daily/2021-05-11.md'
      - '2021-05-10': 'daily/2021-05-10.md'
      - '2021-05-09': 'daily/2021-05-09.md'
      - '2021-05-06': 'daily/2021-05-06.md'
      - '2021-05-04': 'daily/2021-05-04.md'
      - '2021-05-03': 'daily/2021-05-03.md'
      - '2021-05-02': 'daily/2021-05-02.md'
      - '2021-05-01': 'daily/2021-05-01.md'
    - 2021년 4월:
      - '2021-04-30': 'daily/2021-04-30.md'
      - '2021-04-29': 'daily/2021-04-29.md'
      - '2021-04-28': 'daily/2021-04-28.md'
      - '2021-04-27': 'daily/2021-04-27.md'
      - '2021-04-24': 'daily/2021-04-24.md'
      - '2021-04-23': 'daily/2021-04-23.md'
      - '2021-04-19': 'daily/2021-04-19.md'
      - '2021-04-18': 'daily/2021-04-18.md'
      - '2021-04-17': 'daily/2021-04-17.md'
      - '2021-04-16': 'daily/2021-04-16.md'
      - '2021-04-15': 'daily/2021-04-15.md'
      - '2021-04-14': 'daily/2021-04-14.md'
      - '2021-04-10': 'daily/2021-04-10.md'
      - '2021-04-09': 'daily/2021-04-09.md'
      - '2021-04-08': 'daily/2021-04-08.md'
      - '2021-04-07': 'daily/2021-04-07.md'
      - '2021-04-06': 'daily/2021-04-06.md'
    - 2021년 3월:
      - '2021-03-29': 'daily/2021-03-29.md'
      - '2021-03-28': 'daily/2021-03-28.md'
      - '2021-03-24': 'daily/2021-03-24.md'
      - '2021-03-22': 'daily/2021-03-22.md'
      - '2021-03-11': 'daily/2021-03-11.md'
      - '2021-03-11-2': 'daily/2021-03-11-2.md'
      - '2021-03-09': 'daily/2021-03-09.md'
      - '2021-03-04': 'daily/2021-03-04.md'
      - '2021-03-01': 'daily/2021-03-01.md'
    - 2021년 2월:
      - '2021-02-22': 'daily/2021-02-22.md'
      - '2021-02-21': 'daily/2021-02-21.md'
    
    
